stages:
  - workspace
  - env
  - build

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_TLS_CERTDIR: ""
  PROJECT_VERSION: ${CI_COMMIT_REF_SLUG}
  DOCKER_REGISTRY: docker.justinkonratt.com
  ORGANIZATION: codesdowork
  PROJECT: monorepo
  IMAGE_BASE: ${DOCKER_REGISTRY}/${ORGANIZATION}/${PROJECT}
  DOCKER_VERSION: 27.2.1
  DEPS_CACHE_POLICY: pull
  ENV_CACHE_POLICY: pull

default:
  image: ${IMAGE_BASE}/workspace:${PROJECT_VERSION}
  services:
    - name: docker:${DOCKER_VERSION}-dind
      alias: docker
  cache:
    - key:
        files:
          - pnpm-lock.yaml
      paths:
        - node_modules
      policy: $DEPS_CACHE_POLICY
    - key: nx-cache
      paths:
        - .nx
    - key: cache-${CI_COMMIT_SHA}
      paths:
        - ./.env
        - ./packages/**/.env
        - ./*.pem
        - ./packages/**/*.pem
      policy: $ENV_CACHE_POLICY
  before_script:
    - export PATH="./node_modules/.bin:$PATH"
    - docker login -u ${DOCKER_HUB_USER} -p ${DOCKER_HUB_PASSWORD}
    - docker login -u ${DOCKER_REGISTRY_USER} -p ${DOCKER_REGISTRY_PASSWORD} ${DOCKER_REGISTRY}

build workspace image:
  stage: workspace
  image: docker:${DOCKER_VERSION}
  cache: []
  script:
    - docker compose -f docker-compose-workspace.yaml build --push base
    - docker compose -f docker-compose-workspace.yaml build --push workspace

generate env files:
  stage: env
  variables:
    ENV_CACHE_POLICY: push
  script:
    - nx g env-files TEST,PROD ${BITWARDEN_USER} ${BITWARDEN_PASSWORD}

build images:
  stage: build
  script:
    - docker compose -f docker-compose-workspace.yaml build workspace-deps
    - nx build-image music-downloader
