x-build-args:
  build: &build-args
    args:
      - DOCKER_REGISTRY
      - ORGANIZATION
      - PROJECT

services:
  base:
    build:
      dockerfile: Dockerfile.base
    image: ${DOCKER_REGISTRY}/${ORGANIZATION}/${PROJECT}/base

  workspace:
    build:
      <<: *build-args
      dockerfile: Dockerfile.workspace
    image: ${DOCKER_REGISTRY}/${ORGANIZATION}/${PROJECT}/workspace
