x-build-args:
  build: &build-args
    args:
      - ORGNAIZATION
      - PROJECT
      - IMAGE_BASE
      - PROJECT_VERSION

services:
  base:
    build:
      dockerfile: base.Dockerfile
    image: ${IMAGE_BASE}/base:${PROJECT_VERSION:-latest}

  workspace:
    build:
      <<: *build-args
      dockerfile: workspace.Dockerfile
    environment:
      - TERM=xterm-256color
    image: ${IMAGE_BASE}/workspace:${PROJECT_VERSION:-latest}
    network_mode: host
    tty: true
    volumes:
      - .:/workspace
      - /workspace/node_modules
      - ${PNPM_STORE_PATH:-/tmp/.pnpm-store}:/tmp/.pnpm-store
      - //var/run/docker.sock:/var/run/docker.sock

  workspace-deps:
    build:
      <<: *build-args
      dockerfile: workspace-deps.Dockerfile
    image: ${IMAGE_BASE}/workspace-deps:${PROJECT_VERSION:-latest}
