name: ${STACK_NAME}_workspace

x-build-args:
  build: &build-args
    args:
      - IMAGE_BASE

services:
  base:
    build:
      dockerfile: base.Dockerfile
    image: ${IMAGE_BASE}/base

  workspace:
    build:
      <<: *build-args
      dockerfile: workspace.Dockerfile
    environment:
      - TERM=xterm-256color
    image: ${IMAGE_BASE}/workspace:${WORKSPACE_VERSION:-latest}
    network_mode: host
    tty: true
    volumes:
      - .:/workspace
      - /workspace/node_modules
      - ${PNPM_STORE_PATH}:/tmp/.pnpm-store
      - //var/run/docker.sock:/var/run/docker.sock
