services:
  db:
    container_name: monorepo-private-db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    healthcheck:
      test: pg_isready -U postgres
    image: postgres:15-alpine
    ports:
      - 5432:5432

  dev:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: monorepo-private-dev
    environment:
      - HOST=0.0.0.0
      - NEXT_WEBPACK_USEPOLLING=1
    image: codedowork/monorepo-private/dev
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - /app/node_modules
