services:
  base:
    build:
      dockerfile: Dockerfile.base
    image: ${DOCKER_REGISTRY}/${ORGANIZATION}/${PROJECT}/base

  workspace:
    build:
      args:
        - DOCKER_REGISTRY
        - ORGANIZATION
        - PROJECT
      dockerfile: Dockerfile.workspace
    entrypoint: sh
    image: ${DOCKER_REGISTRY}/${ORGANIZATION}/${PROJECT}/workspace
    network_mode: host
    tty: true
    volumes:
      - .:/app
      - /app/node_modules
      - //var/run/docker.sock:/var/run/docker.sock
