FROM node:19-alpine

# create data directory for mounted volumes, which is backed up
RUN mkdir /data

# install rsnapshot for backups
RUN apk add rsnapshot

WORKDIR /app
RUN yarn config set strict-ssl false

ENTRYPOINT rsnapshot configtest && crond && yarn && yarn start
