ssl_certificate /etc/letsencrypt/live/justinkonratt.de/fullchain.pem;
ssl_certificate_key /etc/letsencrypt/live/justinkonratt.de/privkey.pem;

map $remote_addr $is_private_ip {
    default false;
    192.168.192.243 false;
    ~^192\.168\.192\. true;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name watest-default.example.com;
    access_by_lua_file /etc/nginx/lua/access.lua;

    location / {
        proxy_pass http://atest:80;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name atest.justinkonratt.de;

    location /callback-auth {
        access_by_lua_file /etc/nginx/lua/access.lua;
    }

    location /hello {
        access_by_lua_file /etc/nginx/lua/access.lua;
        proxy_pass http://atest:3000;
    }

    location / {
        proxy_pass http://atest:3000;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name hello.example.com;
    access_by_lua_file /etc/nginx/lua/access.lua;

    location / {
        proxy_pass http://test:80;
    }
}