export const Icons: Record<string, string> = {
    "mdi:email": "icon-[mdi--email]",
    "mdi:web": "icon-[mdi--web]",
    "mdi:github": "icon-[mdi--github]",
    "mdi:youtube": "icon-[mdi--youtube]",
    "ic:baseline-phone": "icon-[ic--baseline-phone]",
    "logos:adobe-xd": "icon-[logos--adobe-xd]",
    "logos:android-icon": "icon-[logos--android-icon]",
    "devicon:angular": "icon-[devicon--angular]",
    "devicon:astro": "icon-[devicon--astro]",
    "devicon:bootstrap": "icon-[devicon--bootstrap]",
    "devicon:csharp": "icon-[devicon--csharp]",
    "devicon:cplusplus": "icon-[devicon--cplusplus]",
    "devicon:cloudflare": "icon-[devicon--cloudflare]",
    "simple-icons:directus": "icon-[simple-icons--directus]",
    "logos:docker-icon": "icon-[logos--docker-icon]",
    "arcticons:ankiconnect-android": "icon-[arcticons--ankiconnect-android]",
    "skill-icons:expressjs-dark": "icon-[skill-icons--expressjs-dark]",
    "devicon-plain:fastify": "icon-[devicon-plain--fastify]",
    "vscode-icons:file-type-gitlab": "icon-[vscode-icons--file-type-gitlab]",
    "devicon:grafana": "icon-[devicon--grafana]",
    "vscode-icons:file-type-graphql": "icon-[vscode-icons--file-type-graphql]",
    "devicon:junit": "icon-[devicon--junit]",
    "devicon:java": "icon-[devicon--java]",
    "material-icon-theme:jest": "icon-[material-icon-theme--jest]",
    "devicon:jetpackcompose": "icon-[devicon--jetpackcompose]",
    "devicon:kotlin": "icon-[devicon--kotlin]",
    "devicon:mariadb": "icon-[devicon--mariadb]",
    "material-symbols:markdown": "icon-[material-symbols--markdown]",
    "vscode-icons:file-type-mermaid": "icon-[vscode-icons--file-type-mermaid]",
    "devicon:mongodb": "icon-[devicon--mongodb]",
    "vscode-icons:file-type-nx": "icon-[vscode-icons--file-type-nx]",
    "devicon:nestjs": "icon-[devicon--nestjs]",
    "simple-icons:netdata": "icon-[simple-icons--netdata]",
    "devicon:nextjs": "icon-[devicon--nextjs]",
    "material-icon-theme:nginx": "icon-[material-icon-theme--nginx]",
    "logos:nodejs-icon": "icon-[logos--nodejs-icon]",
    "ri:openai-fill": "icon-[ri--openai-fill]",
    "devicon:podman": "icon-[devicon--podman]",
    "devicon:postgresql": "icon-[devicon--postgresql]",
    "lineicons:prisma": "icon-[lineicons--prisma]",
    "devicon:prometheus": "icon-[devicon--prometheus]",
    "devicon:puppeteer": "icon-[devicon--puppeteer]",
    "vscode-icons:file-type-python": "icon-[vscode-icons--file-type-python]",
    "devicon:pytorch": "icon-[devicon--pytorch]",
    "devicon:react": "icon-[devicon--react]",
    "devicon:reactnative-wordmark": "icon-[devicon--reactnative-wordmark]",
    "logos:sap": "icon-[logos--sap]",
    "devicon:sqlite": "icon-[devicon--sqlite]",
    "devicon:spring": "icon-[devicon--spring]",
    "logos:strapi-icon": "icon-[logos--strapi-icon]",
    "devicon:svelte": "icon-[devicon--svelte]",
    "devicon:swagger": "icon-[devicon--swagger]",
    "devicon:trpc": "icon-[devicon--trpc]",
    "devicon:tailwindcss": "icon-[devicon--tailwindcss]",
    "devicon:tensorflow": "icon-[devicon--tensorflow]",
    "logos:typeorm": "icon-[logos--typeorm]",
    "vscode-icons:file-type-typescript-official":
        "icon-[vscode-icons--file-type-typescript-official]",
    "simple-icons:vitepress": "icon-[simple-icons--vitepress]",
    "devicon:vitest": "icon-[devicon--vitest]",
    "devicon:vuejs": "icon-[devicon--vuejs]",
    "fa6-brands:wpforms": "icon-[fa6-brands--wpforms]",
    "simple-icons:mlflow": "icon-[simple-icons--mlflow]",
};

export const LanguageIcons: Record<string, string> = {
    en: "icon-[circle-flags--en]",
    de: "icon-[circle-flags--de]",
};
