services:
  workspace:
    environment:
      - TERM=xterm-256color
    image: ${IMAGE_BASE}/workspace:${PROJECT_VERSION:-latest}
    network_mode: host
    tty: true
    volumes:
      - ../..:/workspace
      - /workspace/node_modules
      - /workspace/.nx
      - ${PNPM_STORE_PATH:-/tmp/.pnpm-store}:/tmp/.pnpm-store
      - //var/run/docker.sock:/var/run/docker.sock
