name = "just-maintenance"
main = "worker.js"
compatibility_date = "2023-08-23"

minify = true

[build]
command = "nx build just-maintenance"

[site]
bucket = "../../../dist/packages/just-maintenance"
