FROM <%= baseImage %> AS workspace
WORKDIR /app

<%- installGit %>

RUN npm i -g @antfu/ni
<%- preInstall -%>

COPY package.json .
COPY *lock* .
RUN ni
<%- postInstall -%>
<%- preCopy -%>

COPY . .
<%- preChecks -%>

RUN npx nx format:check
<%- end -%>