export interface RawBSLItem {
    "BLS Code": string;
    Lebensmittelbezeichnung: string;
    "Food name": string;
    "ENERCJ Energie (Kilojoule) [kJ/100g]": bigint;
    "ENERCJ Datenherkunft": string;
    "ENERCJ Referenz": string;
    "ENERCC Energie (Kilokalorien) [kcal/100g]": bigint;
    "ENERCC Datenherkunft": string;
    "ENERCC Referenz": string;
    "WATER Wasser [g/100g]": string;
    "WATER Datenherkunft": string;
    "WATER Referenz": string;
    "PROT625 Protein (Nx6,25) [g/100g]": string;
    "PROT625 Datenherkunft": string;
    "PROT625 Referenz": string;
    "FAT Fett [g/100g]": string;
    "FAT Datenherkunft": string;
    "FAT Referenz": string;
    "CHO Kohlenhydrate, verfügbar [g/100g]": number;
    "CHO Datenherkunft": string;
    "CHO Referenz": string;
    "FIBT Ballaststoffe, gesamt [g/100g]": string;
    "FIBT Datenherkunft": string;
    "FIBT Referenz": string;
    "ALC Alkohol (Ethanol) [g/100g]": string;
    "ALC Datenherkunft": string;
    "ALC Referenz": string;
    "OA Organische Säuren, gesamt [g/100g]": string;
    "OA Datenherkunft": string;
    "OA Referenz": string;
    "ASH Rohasche [g/100g]": string;
    "ASH Datenherkunft": string;
    "ASH Referenz": string;
    "VITA Vitamin A, Retinol-Äquivalent (RE) [µg/100g]": string;
    "VITA Datenherkunft": string;
    "VITA Referenz": string;
    "VITAA Vitamin A, Retinol-Aktivitäts-Äquivalent (RAE) [µg/100g]": string;
    "VITAA Datenherkunft": string;
    "VITAA Referenz": string;
    "RETOL Retinol [µg/100g]": string;
    "RETOL Datenherkunft": string;
    "RETOL Referenz": string;
    "CARTB Beta‑Carotin [µg/100g]": string;
    "CARTB Datenherkunft": string;
    "CARTB Referenz": string;
    "CAROTPAXB Carotinoide, außer Beta-Carotin [µg/100g]": string;
    "CAROTPAXB Datenherkunft": string;
    "CAROTPAXB Referenz": string;
    "VITD Vitamin D [µg/100g]": string;
    "VITD Datenherkunft": string;
    "VITD Referenz": string;
    "CHOCAL Vitamin D3 (Cholecalciferol) [µg/100g]": string;
    "CHOCAL Datenherkunft": string;
    "CHOCAL Referenz": string;
    "ERGCAL Vitamin D2 (Ergocalciferol) [µg/100g]": string;
    "ERGCAL Datenherkunft": string;
    "ERGCAL Referenz": string;
    "VITE Vitamin E (Alpha-Tocopherol) [mg/100g]": string;
    "VITE Datenherkunft": string;
    "VITE Referenz": string;
    "TOCPHA Alpha‑Tocopherol [mg/100g]": string;
    "TOCPHA Datenherkunft": string;
    "TOCPHA Referenz": string;
    "TOCPHB Beta-Tocopherol [mg/100g]": string;
    "TOCPHB Datenherkunft": string;
    "TOCPHB Referenz": string;
    "TOCPHG Gamma-Tocopherol [mg/100g]": string;
    "TOCPHG Datenherkunft": string;
    "TOCPHG Referenz": string;
    "TOCPHD Delta-Tocopherol [mg/100g]": string;
    "TOCPHD Datenherkunft": string;
    "TOCPHD Referenz": string;
    "TOCTRA Alpha-Tocotrienol [mg/100g]": string;
    "TOCTRA Datenherkunft": string;
    "TOCTRA Referenz": string;
    "VITK Vitamin K [µg/100g]": string;
    "VITK Datenherkunft": string;
    "VITK Referenz": string;
    "VITK1 Vitamin K1 (Phyllochinon) [µg/100g]": string;
    "VITK1 Datenherkunft": string;
    "VITK1 Referenz": string;
    "VITK2 Vitamin K2 (Menachinone) [µg/100g]": string;
    "VITK2 Datenherkunft": string;
    "VITK2 Referenz": string;
    "THIA Vitamin B1 (Thiamin) [mg/100g]": string;
    "THIA Datenherkunft": string;
    "THIA Referenz": string;
    "RIBF Vitamin B2 (Riboflavin) [mg/100g]": string;
    "RIBF Datenherkunft": string;
    "RIBF Referenz": string;
    "NIAEQ Niacin-Äquivalent [mg/100g]": string;
    "NIAEQ Datenherkunft": string;
    "NIAEQ Referenz": string;
    "NIA Niacin [mg/100g]": string;
    "NIA Datenherkunft": string;
    "NIA Referenz": string;
    "PANTAC Pantothensäure [mg/100g]": string;
    "PANTAC Datenherkunft": string;
    "PANTAC Referenz": string;
    "VITB6 Vitamin B6 [µg/100g]": string;
    "VITB6 Datenherkunft": string;
    "VITB6 Referenz": string;
    "BIOT Biotin [µg/100g]": string;
    "BIOT Datenherkunft": string;
    "BIOT Referenz": string;
    "FOL Folat-Äquivalent [µg/100g]": string;
    "FOL Datenherkunft": string;
    "FOL Referenz": string;
    "FOLFD Folat [µg/100g]": string;
    "FOLFD Datenherkunft": string;
    "FOLFD Referenz": string;
    "FOLAC Folsäure, synthetisch [µg/100g]": string;
    "FOLAC Datenherkunft": string;
    "FOLAC Referenz": string;
    "VITB12 Vitamin B12 (Cobalamine) [µg/100g]": string;
    "VITB12 Datenherkunft": string;
    "VITB12 Referenz": string;
    "VITC Vitamin C [mg/100g]": string;
    "VITC Datenherkunft": string;
    "VITC Referenz": string;
    "NACL Salz (Natriumchlorid) [g/100g]": number;
    "NACL Datenherkunft": string;
    "NACL Referenz": string;
    "NA Natrium [mg/100g]": string;
    "NA Datenherkunft": string;
    "NA Referenz": string;
    "CLD Chlorid [mg/100g]": string;
    "CLD Datenherkunft": string;
    "CLD Referenz": string;
    "K Kalium [mg/100g]": string;
    "K Datenherkunft": string;
    "K Referenz": string;
    "CA Calcium [mg/100g]": string;
    "CA Datenherkunft": string;
    "CA Referenz": string;
    "MG Magnesium [mg/100g]": string;
    "MG Datenherkunft": string;
    "MG Referenz": string;
    "P Phosphor [mg/100g]": string;
    "P Datenherkunft": string;
    "P Referenz": string;
    "S Schwefel [mg/100g]": string;
    "S Datenherkunft": string;
    "S Referenz": string;
    "FE Eisen [mg/100g]": string;
    "FE Datenherkunft": string;
    "FE Referenz": string;
    "ZN Zink [mg/100g]": number;
    "ZN Datenherkunft": string;
    "ZN Referenz": string;
    "ID Iodid [µg/100g]": string;
    "ID Datenherkunft": string;
    "ID Referenz": string;
    "CU Kupfer [µg/100g]": string;
    "CU Datenherkunft": string;
    "CU Referenz": string;
    "MN Mangan [µg/100g]": string;
    "MN Datenherkunft": string;
    "MN Referenz": string;
    "FD Fluorid [µg/100g]": string;
    "FD Datenherkunft": string;
    "FD Referenz": string;
    "CR Chrom [µg/100g]": string;
    "CR Datenherkunft": string;
    "CR Referenz": string;
    "MO Molybdän [µg/100g]": string;
    "MO Datenherkunft": string;
    "MO Referenz": string;
    "ACEAC Essigsäure [g/100g]": string;
    "ACEAC Datenherkunft": string;
    "ACEAC Referenz": string;
    "CITAC Zitronensäure [g/100g]": string;
    "CITAC Datenherkunft": string;
    "CITAC Referenz": string;
    "LACAC Milchsäure [g/100g]": string;
    "LACAC Datenherkunft": string;
    "LACAC Referenz": string;
    "MALAC Äpfelsäure [g/100g]": string;
    "MALAC Datenherkunft": string;
    "MALAC Referenz": string;
    "TARAC Weinsäure [g/100g]": string;
    "TARAC Datenherkunft": string;
    "TARAC Referenz": string;
    "POLYL Zuckeralkohole, gesamt [g/100g]": string;
    "POLYL Datenherkunft": string;
    "POLYL Referenz": string;
    "MANTL Mannit [g/100g]": string;
    "MANTL Datenherkunft": string;
    "MANTL Referenz": string;
    "SORTL Sorbit [g/100g]": string;
    "SORTL Datenherkunft": string;
    "SORTL Referenz": string;
    "XYLTL Xylit [g/100g]": string;
    "XYLTL Datenherkunft": string;
    "XYLTL Referenz": string;
    "MNSAC Monosaccharide, gesamt [g/100g]": string;
    "MNSAC Datenherkunft": string;
    "MNSAC Referenz": string;
    "GLUS Glucose [g/100g]": string;
    "GLUS Datenherkunft": string;
    "GLUS Referenz": string;
    "FRUS Fructose [g/100g]": string;
    "FRUS Datenherkunft": string;
    "FRUS Referenz": string;
    "GALS Galactose [g/100g]": string;
    "GALS Datenherkunft": string;
    "GALS Referenz": string;
    "DISAC Disaccharide, gesamt [g/100g]": string;
    "DISAC Datenherkunft": string;
    "DISAC Referenz": string;
    "SUCS Saccharose [g/100g]": string;
    "SUCS Datenherkunft": string;
    "SUCS Referenz": string;
    "MALS Maltose [g/100g]": string;
    "MALS Datenherkunft": string;
    "MALS Referenz": string;
    "LACS Lactose [g/100g]": string;
    "LACS Datenherkunft": string;
    "LACS Referenz": string;
    "SUGAR Zucker (Mono- und Disaccharide), gesamt [g/100g]": number;
    "SUGAR Datenherkunft": string;
    "SUGAR Referenz": string;
    "OLSAC Oligosaccharide, verfügbar [g/100g]": string;
    "OLSAC Datenherkunft": string;
    "OLSAC Referenz": string;
    "STARCH Stärke (Stärke, Glykogen, Dextrine) [g/100g]": string;
    "STARCH Datenherkunft": string;
    "STARCH Referenz": string;
    "FIBLMW Ballaststoffe, niedermolekular [g/100g]": string;
    "FIBLMW Datenherkunft": string;
    "FIBLMW Referenz": string;
    "FIBHMW Ballaststoffe, hochmolekular [g/100g]": string;
    "FIBHMW Datenherkunft": string;
    "FIBHMW Referenz": string;
    "FIBINS Ballaststoffe, wasserunlöslich [g/100g]": string;
    "FIBINS Datenherkunft": string;
    "FIBINS Referenz": string;
    "FIBSOL Ballaststoffe, wasserlöslich [g/100g]": string;
    "FIBSOL Datenherkunft": string;
    "FIBSOL Referenz": string;
    "FIBHMWS Ballaststoffe, hochmolekular, wasserlöslich [g/100g]": string;
    "FIBHMWS Datenherkunft": string;
    "FIBHMWS Referenz": string;
    "FIBHMWI Ballaststoffe, hochmolekular, wasserunlöslich [g/100g]": string;
    "FIBHMWI Datenherkunft": string;
    "FIBHMWI Referenz": string;
    "FASAT Fettsäuren, gesättigt, gesamt [g/100g]": string;
    "FASAT Datenherkunft": string;
    "FASAT Referenz": string;
    "F4:0 Fettsäure C4:0 (Buttersäure) [g/100g]": string;
    "F4:0 Datenherkunft": string;
    "F4:0 Referenz": string;
    "F6:0 Fettsäure C6:0 (Capronsäure) [g/100g]": string;
    "F6:0 Datenherkunft": string;
    "F6:0 Referenz": string;
    "F8:0 Fettsäure C8:0 (Caprylsäure) [g/100g]": string;
    "F8:0 Datenherkunft": string;
    "F8:0 Referenz": string;
    "F10:0 Fettsäure C10:0 (Caprinsäure) [g/100g]": string;
    "F10:0 Datenherkunft": string;
    "F10:0 Referenz": string;
    "F12:0 Fettsäure C12:0 (Laurinsäure) [g/100g]": string;
    "F12:0 Datenherkunft": string;
    "F12:0 Referenz": string;
    "F14:0 Fettsäure C14:0 (Myristinsäure) [g/100g]": string;
    "F14:0 Datenherkunft": string;
    "F14:0 Referenz": string;
    "F15:0 Fettsäure C15:0 (Pentadecylsäure) [g/100g]": string;
    "F15:0 Datenherkunft": string;
    "F15:0 Referenz": string;
    "F16:0 Fettsäure C16:0 (Palmitinsäure) [g/100g]": string;
    "F16:0 Datenherkunft": string;
    "F16:0 Referenz": string;
    "F17:0 Fettsäure C17:0 (Margarinsäure) [g/100g]": string;
    "F17:0 Datenherkunft": string;
    "F17:0 Referenz": string;
    "F18:0 Fettsäure C18:0 (Stearinsäure) [g/100g]": string;
    "F18:0 Datenherkunft": string;
    "F18:0 Referenz": string;
    "F20:0 Fettsäure C20:0 (Arachinsäure) [g/100g]": string;
    "F20:0 Datenherkunft": string;
    "F20:0 Referenz": string;
    "F22:0 Fettsäure C22:0 (Behensäure) [g/100g]": string;
    "F22:0 Datenherkunft": string;
    "F22:0 Referenz": string;
    "F24:0 Fettsäure C24:0 (Lignocerinsäure) [g/100g]": string;
    "F24:0 Datenherkunft": string;
    "F24:0 Referenz": string;
    "FAMS Fettsäure, einfach ungesättigt, gesamt [g/100g]": string;
    "FAMS Datenherkunft": string;
    "FAMS Referenz": string;
    "F14:1CN5 Fettsäure C14:1 n-5 cis (Myristoleinsäure) [g/100g]": string;
    "F14:1CN5 Datenherkunft": string;
    "F14:1CN5 Referenz": string;
    "F16:1CN7 Fettsäure C16:1 n-7 cis (Palmitoleinsäure) [g/100g]": string;
    "F16:1CN7 Datenherkunft": string;
    "F16:1CN7 Referenz": string;
    "F18:1CN7 Fettsäure C18:1 n-7 cis (Vaccensäure) [g/100g]": string;
    "F18:1CN7 Datenherkunft": string;
    "F18:1CN7 Referenz": string;
    "F18:1CN9 Fettsäure C18:1 n-9 cis (Ölsäure) [g/100g]": string;
    "F18:1CN9 Datenherkunft": string;
    "F18:1CN9 Referenz": string;
    "F20:1CN9 Fettsäure C20:1 n-9 cis (Gondosäure) [g/100g]": string;
    "F20:1CN9 Datenherkunft": string;
    "F20:1CN9 Referenz": string;
    "F22:1CN9 Fettsäure C22:1 n-9 cis (Erucasäure) [g/100g]": string;
    "F22:1CN9 Datenherkunft": string;
    "F22:1CN9 Referenz": string;
    "FAPU Fettsäuren, mehrfach ungesättigt, gesamt [g/100g]": string;
    "FAPU Datenherkunft": string;
    "FAPU Referenz": string;
    "FAPUN3 Fettsäuren, mehrfach ungesättigt n-3 (Omega-3), gesamt [g/100g]": string;
    "FAPUN3 Datenherkunft": string;
    "FAPUN3 Referenz": string;
    "F18:3CN3 Fettsäure C18:3 n-3 all-cis (Alpha-Linolensäure) [g/100g]": string;
    "F18:3CN3 Datenherkunft": string;
    "F18:3CN3 Referenz": string;
    "F18:4CN3 Fettsäure C18:4 n-3 all-cis (Stearidonsäure) [g/100g]": string;
    "F18:4CN3 Datenherkunft": string;
    "F18:4CN3 Referenz": string;
    "F20:5CN3 Fettsäure C20:5 n-3 all-cis (Eicosapentaensäure) [g/100g]": string;
    "F20:5CN3 Datenherkunft": string;
    "F20:5CN3 Referenz": string;
    "F22:5CN3 Fettsäure C22:5 n-3 all-cis (Docosapentaensäure) [g/100g]": string;
    "F22:5CN3 Datenherkunft": string;
    "F22:5CN3 Referenz": string;
    "F22:6CN3 Fettsäure C22:6 n-3 all-cis (Docosahexaensäure) [g/100g]": string;
    "F22:6CN3 Datenherkunft": string;
    "F22:6CN3 Referenz": string;
    "FAPUN6 Fettsäuren, mehrfach ungesättigt n-6 (Omega-6), gesamt [g/100g]": string;
    "FAPUN6 Datenherkunft": string;
    "FAPUN6 Referenz": string;
    "F18:2CN6 Fettsäure C18:2 n-6 cis, cis (Linolsäure) [g/100g]": string;
    "F18:2CN6 Datenherkunft": string;
    "F18:2CN6 Referenz": string;
    "F18:2C9T11 Fettsäure C18:2 n-7 cis 9, trans 11 (konjugierte Linolsäure) [g/100g]": string;
    "F18:2C9T11 Datenherkunft": string;
    "F18:2C9T11 Referenz": string;
    "F18:3CN6 Fettsäure C18:3 n-6 all-cis (Gamma-Linolensäure) [g/100g]": string;
    "F18:3CN6 Datenherkunft": string;
    "F18:3CN6 Referenz": string;
    "F20:2CN6 Fettsäure C20:2 n-6 all-cis (Eicosadiensäure) [g/100g]": string;
    "F20:2CN6 Datenherkunft": string;
    "F20:2CN6 Referenz": string;
    "F20:3CN6 Fettsäure C20:3 n-6 all-cis (Dihomogamma-Linolensäure) [g/100g]": string;
    "F20:3CN6 Datenherkunft": string;
    "F20:3CN6 Referenz": string;
    "F20:4CN6 Fettsäure C20:4 n-6 all-cis (Arachidonsäure) [g/100g]": string;
    "F20:4CN6 Datenherkunft": string;
    "F20:4CN6 Referenz": string;
    "FAX Fettsäuren, sonstige [g/100g]": string;
    "FAX Datenherkunft": string;
    "FAX Referenz": string;
    "CHORL Cholesterin [mg/100g]": string;
    "CHORL Datenherkunft": string;
    "CHORL Referenz": string;
    "AAE9 Aminosäuren, unentbehrlich, gesamt [g/100g]": string;
    "AAE9 Datenherkunft": string;
    "AAE9 Referenz": string;
    "ALA Alanin [g/100g]": string;
    "ALA Datenherkunft": string;
    "ALA Referenz": string;
    "ARG Arginin [g/100g]": string;
    "ARG Datenherkunft": string;
    "ARG Referenz": string;
    "ASP Asparaginsäure, inklusive Asparagin [g/100g]": string;
    "ASP Datenherkunft": string;
    "ASP Referenz": string;
    "CYSTE Cystein [g/100g]": string;
    "CYSTE Datenherkunft": string;
    "CYSTE Referenz": string;
    "GLU Glutaminsäure, inklusive Glutamin [g/100g]": string;
    "GLU Datenherkunft": string;
    "GLU Referenz": string;
    "GLY Glycin [g/100g]": string;
    "GLY Datenherkunft": string;
    "GLY Referenz": string;
    "HIS Histidin [g/100g]": string;
    "HIS Datenherkunft": string;
    "HIS Referenz": string;
    "ILE Isoleucin [g/100g]": string;
    "ILE Datenherkunft": string;
    "ILE Referenz": string;
    "LEU Leucin [g/100g]": string;
    "LEU Datenherkunft": string;
    "LEU Referenz": string;
    "LYS Lysin [g/100g]": string;
    "LYS Datenherkunft": string;
    "LYS Referenz": string;
    "MET Methionin [g/100g]": string;
    "MET Datenherkunft": string;
    "MET Referenz": string;
    "PHE Phenylalanin [g/100g]": string;
    "PHE Datenherkunft": string;
    "PHE Referenz": string;
    "PRO Prolin [g/100g]": string;
    "PRO Datenherkunft": string;
    "PRO Referenz": string;
    "SER Serin [g/100g]": string;
    "SER Datenherkunft": string;
    "SER Referenz": string;
    "THR Threonin [g/100g]": string;
    "THR Datenherkunft": string;
    "THR Referenz": string;
    "TRP Tryptophan [g/100g]": string;
    "TRP Datenherkunft": string;
    "TRP Referenz": string;
    "TYR Tyrosin [g/100g]": string;
    "TYR Datenherkunft": string;
    "TYR Referenz": string;
    "VAL Valin [g/100g]": string;
    "VAL Datenherkunft": string;
    "VAL Referenz": string;
    "NT Stickstoff, gesamt [g/100g]": string;
    "NT Datenherkunft": string;
    "NT Referenz": string;
    Hinweis: string | null;
}
