name: NX CI

on:
  pull_request:
    branches:
      - master
      - develop
      - release/**
      - feature/**
      - bugfix/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Use Nx
        uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: develop

      - run: pnpm i
      - run: pnpm run format:check
      - run: pnpm run test
      - run: pnpm run lint
      - run: pnpm run build
